CREATE DATABASE HELP_DESK
USE HELP_DESK


CREATE TABLE TB_ACESSO
(
CD_ACESSO INT NOT NULL
,NM_TIPOACESSO VARCHAR(255) NOT NULL
, CONSTRAINT PK_TB_ACESSO PRIMARY KEY(CD_ACESSO)
)

INSERT INTO TB_ACESSO VALUES (1, 'TECNICO')
INSERT INTO TB_ACESSO VALUES (2, 'USUARIO')

CREATE TABLE TB_FUNCIONARIO
(CD_FUNCIONARIO INT IDENTITY(1,1)
,NM_FUNCIONARIO VARCHAR(255) NOT NULL
,NR_ANDAR INT NOT NULL
,NR_RAMAL INT NOT NULL
,NR_CELULAR INT NOT NULL
,NM_EMAIL VARCHAR(255) NOT NULL
,NR_SALA INT NOT NULL
,DT_ADMISSAO VARCHAR(255) NOT NULL
,NR_MATRICULA INT UNIQUE NOT NULL
,NR_CPF VARCHAR(11) NOT NULL
,CD_ACESSO INT NOT NULL
,NR_SITUACAO INT NOT NULL
,NM_SENHA VARCHAR(255) NOT NULL
,CONSTRAINT PK_TB_FUNCIONARIO PRIMARY KEY (CD_FUNCIONARIO)
,CONSTRAINT FK_TB_ACESSO FOREIGN KEY (CD_ACESSO) REFERENCES TB_ACESSO(CD_ACESSO)
)
INSERT INTO TB_FUNCIONARIO(NM_FUNCIONARIO, NR_ANDAR,NR_RAMAL,NR_CELULAR, NM_EMAIL, NR_SALA,DT_ADMISSAO,NR_MATRICULA, NR_CPF, CD_ACESSO, NR_SITUACAO,NM_SENHA) VALUES ('DANIEL', 3,3017, 988049055, 'dcruas@yahoo.com.br', 301, '2018-05-11',20000001,'40339581859', 1, 1, 'UNIPTEC')
INSERT INTO TB_FUNCIONARIO(NM_FUNCIONARIO, NR_ANDAR,NR_RAMAL, NR_CELULAR, NM_EMAIL, NR_SALA,DT_ADMISSAO,NR_MATRICULA, NR_CPF, CD_ACESSO, NR_SITUACAO,NM_SENHA) VALUES ('TESTE', 4, 4041, 988045411, 'dmruas@bol.com.br', 586, '2018-05-11', 20000002,'3226263815', 2, 1, 'UNIPTEC')


CREATE TABLE TB_PROBLEMA
(
CD_PROBLEMA INT PRIMARY KEY NOT NULL
,NM_PROBLEMA VARCHAR(255) NOT NULL
)

INSERT INTO TB_PROBLEMA VALUES(1, 'MÁQUINA NÃO LIGA')
INSERT INTO TB_PROBLEMA VALUES(2, 'INTERNET NÃO PEGA')
INSERT INTO TB_PROBLEMA VALUES(3, 'IMPRESSORA NÃO FUCNIONA')
INSERT INTO TB_PROBLEMA VALUES(4, 'SISTEMA TRAVANDO')
INSERT INTO TB_PROBLEMA VALUES(5, 'PROBLEMA COM A MAQUINA')
INSERT INTO TB_PROBLEMA VALUES(6, 'ACESSÓRIO COM PROBLEMA')

CREATE TABLE TB_STATUS
(
CD_STATUS INT PRIMARY KEY NOT NULL
,NM_STATUS VARCHAR(255) NOT NULL
)

INSERT INTO TB_STATUS VALUES(1, 'PENDENTE')
INSERT INTO TB_STATUS VALUES(2, 'PENDENTE COM ATRASO')
INSERT INTO TB_STATUS VALUES(3, 'ENCERRADO')
INSERT INTO TB_STATUS VALUES(4, 'ENCERRADO COM ATRASO')

CREATE TABLE TB_AVALIACAO
(
CD_AVALIACAO INT PRIMARY KEY,
NM_STATUS VARCHAR(255) NOT NULL

)

INSERT INTO TB_AVALIACAO VALUES(1, 'MUITO INSATISFEITO')
INSERT INTO TB_AVALIACAO VALUES(2, 'INSATISFEITO')
INSERT INTO TB_AVALIACAO VALUES(3, 'REGULAR')
INSERT INTO TB_AVALIACAO VALUES(4, 'SATISFEITO')
INSERT INTO TB_AVALIACAO VALUES(5, 'MUITO SATISFEITO')

CREATE TABLE TB_CHAMADO
(
CD_CHAMADO INT IDENTITY(1,1)
,CD_TECNICO INT NULL
,DT_ABERTURA DATETIME NOT NULL
,DS_JUSTIFICATIVA VARCHAR(255) NULL
,DS_PROBLEMA VARCHAR(255) NOT NULL
, DT_ENCERRAMENTO DATETIME  NULL
, CD_FUNCIONARIO INT NOT NULL
, CD_PROBLEMA INT NOT NULL
, CD_STATUS INT NOT NULL
, CD_AVALIACAO INT NULL
,CONSTRAINT FK_TB_PROBLEMA FOREIGN KEY(CD_PROBLEMA) REFERENCES TB_PROBLEMA(CD_PROBLEMA)
,CONSTRAINT FK_TB_STATUS FOREIGN KEY(CD_STATUS) REFERENCES TB_STATUS(CD_STATUS)
,CONSTRAINT FK_TB_AVALIACAO FOREIGN KEY(CD_AVALIACAO) REFERENCES TB_AVALIACAO(CD_AVALIACAO)
,CONSTRAINT FK_TB_FUNCIONARIO FOREIGN KEY(CD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (CD_FUNCIONARIO)
,CONSTRAINT FK_TB_TECNICO FOREIGN KEY (CD_TECNICO) REFERENCES TB_FUNCIONARIO (CD_FUNCIONARIO)
)

INSERT INTO TB_CHAMADO (DT_ABERTURA, DS_PROBLEMA, CD_FUNCIONARIO, CD_PROBLEMA, CD_STATUS) VALUES ('2018-11-05', 'COMPUTADOR NÃO ESTÁ LIGANDO', 2, 1, 1)



